name: Sanity Tests
on: [ push ]
jobs:
  # https://stackoverflow.com/questions/66261101/using-vagrant-on-github-actions-ideally-incl-virtualbox
  sanity-tests-on-macos:
    runs-on: macos-10.15
    defaults:
      run:
        working-directory: ansible_collections/jclaveau/vagrant

    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
        with:
          path: ansible_collections/jclaveau/vagrant

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install wheel dependency
        run: pip install wheel

      - name: Install Ansible
        run: pip install ansible

      - name: Install python-vagrant dependency
        run: pip install python-vagrant

      - name: Install pycodestyle dependency
        run: pip install pycodestyle

      - name: Install pylint dependency
        run: pip install pylint

      - name: Install six dependency
        run: pip install six

      - name: Install voluptuous dependency
        run: pip install voluptuous

      - name: Install yamllint dependency
        run: pip install yamllint pyyaml

      - name: Run the sanity tests
        run: ansible-test sanity --python 3.8
